### ISSUE TITLE
 Vaadin-demo-snippet "Copy" button can't use shift+tab in Firefox 63

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-demo-helpers#58] opened 2018-10-20 04:52 UTC
Demo: https://cdn.vaadin.com/vaadin-button/2.1.0/demo/#button-basic-demos

When you navigate to copy button it does get focused but after that pressing shift+tab won't move you away from the button

**Comment by web-padawan** [comment] 2019-06-04 07:04
Works in Firefox 66. 

Most likely was caused by one of the issues with initial Shadow DOM implementation in 63, which have been fixed in subsequent releases. So we can close this now.

**Closed by web-padawan** 2019-06-04 07:04 UTC
Labels: in review unscoped
