### ISSUE TITLE
[Question][Documentationa] Are there any examples/demos for converted Polymer 3 compatible Vaadin components?

### ISSUE THREAD

**Issue by tiho2** [vaadin/vaadin-demo-helpers#62] opened 2018-11-09 09:17 UTC

**Comment by tiho2** [comment] 2018-11-12 12:43
Thanks for the clarification.
Maybee polymer 2 based examples will do in my case.
Bower is not used in my company and the connections to bower repositories aren't open. So, in my case, it is easier to setup development env. for polymer 3 as it uses npm.

**Comment by lkraav** [comment] 2018-11-29 22:34
@web-padawan do you think maybe https://github.com/Polymer/polymer-modulizer/issues/405 isn't getting much attention because everything was migrated to https://github.com/Polymer/tools monorepo, and that's where all the eyes and attention are?

**Comment by web-padawan** [comment] 2018-11-30 10:47
@lkraav my feeling is that Polymer team does not want to invest resources to `modulizer` at this point. It has been confirmed to work by us, and does the job for the components themselves, as well as converting tests. AFAIK there are guys in Google who are converting their internal projects from Polymer 1 to something newer, either 2 or 3 - at some point they might want to put more effort.

**Comment by web-padawan** [comment] 2019-06-05 07:04
We are about to start the Polymer 3 and ES modules conversion of all the components.
The progress on demo helpers tracked at #67 (to be started next week).

Closing this one, and sorry about the long delay.

**Closed by web-padawan** 2019-06-05 07:04 UTC
